/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-09-22 15:35:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.Random;

public final class ajax6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Random rand = new Random(System.currentTimeMillis());
	out.println(rand.nextInt(10) + "$" + rand.nextInt(10) + "$" + rand.nextInt(10));

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>简易版股票交易</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var xmlHttp;\r\n");
      out.write("function createXMLHttpRequest() {\r\n");
      out.write("\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\t//适用于DOM2浏览器\r\n");
      out.write("\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t} else if(window.ActiveXObject){\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\txmlHttp = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t} catch (e) {\r\n");
      out.write("\t\t\t// 适用于IE5.5，以及IE更早版本\r\n");
      out.write("\t\t\ttry{\r\n");
      out.write("\t\t\t\txmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t} catch (e){\r\n");
      out.write("                 alert(\"对不起您使用的浏览器版本暂不支持Ajax，请您更换浏览器重试，或升级浏览器！\");\r\n");
      out.write("                 throw e;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getPrice() {\r\n");
      out.write("\tcreateXMLHttpRequest();\r\n");
      out.write("\tvar uri = \"ajax6.jsp\";\r\n");
      out.write("\txmlHttp.open(\"GET\",uri,true);\r\n");
      out.write("\txmlHttp.onreadystatechange = processResponse;\r\n");
      out.write("\txmlHttp.send(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function processResponse(){\r\n");
      out.write("\tif(xmlHttp.readyState == 4){\r\n");
      out.write("\t\tif(xmlHttp.status == 200){\r\n");
      out.write("\t\t\tvar prices = xmlHttp.responseText.split(\"$\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"mysql\").innerHTML = prices[0];\r\n");
      out.write("\t\t\tdocument.getElementById(\"tomcat\").innerHTML = prices[1];\r\n");
      out.write("\t\t\tdocument.getElementById(\"jetty\").innerHTML = prices[2];\r\n");
      out.write("\t\t\t//设置一秒钟后再次发送请求\r\n");
      out.write("\t\t\tsetTimeout(\"getPrice()\",1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("document.body.onload = getPrice;\r\n");
      out.write("</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("<h1>股票交易所</h1>\r\n");
      out.write("MySQL的虚拟股票价格:<div id = \"mysql\" style=\"color:red;font-weight:bold;\"></div>\r\n");
      out.write("Tomcat的虚拟股票价格:<div id = \"tomcat\" style=\"color:blue;font-weight:bold\"></div>\r\n");
      out.write("jetty的虚拟股票价格:<div id = \"jetty\" style = \"color:yellow;font-weight:bold\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
